# Generated by Django 4.2.6 on 2023-10-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_companyaccount_job_jobseekeraccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
