# Generated by Django 4.2.6 on 2023-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_job_company'),
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekeraccount',
            name='jobs_applied',
            field=models.ManyToManyField(blank=True, to='job_management.job'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
