# Generated by Django 4.2.6 on 2023-10-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='', max_length=100)),
                ('job_description', models.CharField(default='', max_length=100)),
                ('salary', models.PositiveBigIntegerField()),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(default='Any', max_length=50)),
                ('job_location', models.CharField(default='', max_length=200)),
                ('industry_type', models.CharField(default='', max_length=200)),
                ('key_skills', models.CharField(max_length=500)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('number_of_openings', models.IntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.companyaccount')),
            ],
        ),
    ]
