# Generated by Django 4.2.6 on 2023-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
